name: Daily VN30 ETL Pipeline

on:
  schedule:
    - cron: '0 9 * * 1-5'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Bước 1 - Tải code từ Github về máy ảo
        uses: actions/checkout@v3
        
      - name: Bước 2 - Cài đặt ngôn ngữ Python cho máy ảo
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Bước 3 - Cài đặt các thư viện cần thiết
        run: |
          pip install pandas vnstock supabase
          
      - name: Bước 4 - Chạy file Python và truyền khóa bảo mật vào
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python main.py
